openapi: 3.0.1
info:
  title: Order API
  version: "2.0"
servers:
  - url: "http://localhost:3000"
paths:
  "/products/{id}":
    parameters:
      - name: id
        schema:
          type: number
        in: path
        required: true
        examples:
          GET_PRODUCT:
            value: 10
          UPDATE_PRODUCT:
            value: 10
          DELETE_PRODUCT:
            value: 20
          INVALID_ID:
            value: "344"
    get:
      summary: Fetch product details
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/Product"
              examples:
                GET_PRODUCT:
                  value:
                    name: "XYZ Phone"
                    type: "gadget"
                    inventory: 10
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
              examples:
                INVALID_ID:
                  value:
                    timestamp: "2023-03-17T12:06:56.177+00:00"
                    status: 404
                    error: "Not Found"
                    message: "Not found"
      operationId: get-product-id
    post:
      summary: Update product details
      operationId: post-products-id
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Update successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                UPDATE_PRODUCT:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/Product"
            examples:
              UPDATE_PRODUCT:
                value:
                  name: "XYZ Fone"
                  type: "gadget"
                  inventory: 10
                  id: 10
    delete:
      summary: Delete a product
      operationId: delete-products-id
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Deletion successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                DELETE_PRODUCT:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
  /products:
    get:
      summary: GET Products based on type
      parameters:
        - name: type
          in: query
          schema:
            $ref: "./common.yaml#/components/schemas/ProductType"
      responses:
        "200":
          description: List of products in the response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "common.yaml#/components/schemas/Product"
    post:
      summary: POST /products
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "common.yaml#/components/schemas/ProductDetails"
      responses:
        "200":
          description: POST /products
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ProductId"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
  /orders:
    post:
      summary: POST /orders
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "common.yaml#/components/schemas/OrderDetails"
            examples:
              CREATE_ORDER:
                value:
                  productid: 10
                  count: 2
                  status: pending
      responses:
        "200":
          description: POST /orders
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/OrderId"
              examples:
                CREATE_ORDER:
                  value:
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
    get:
      summary: Search for orders
      operationId: get-orders
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./common.yaml#/components/schemas/Order"
              examples:
                200_OK:
                  value:
                    - productid: 10
                      count: 2
                      status: "pending"
                      id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      parameters:
        - name: productid
          in: query
          schema:
            type: number
          examples:
            200_OK:
              value: 10
        - name: status
          in: query
          schema:
            type: string
          examples:
            200_OK:
              value: fulfilled
      description: ""
  "/orders/{id}":
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        examples:
          GET_ORDER:
            value: 10
          UPDATE_ORDER:
            value: 10
          DELETE_ORDER:
            value: 20
          INVALID_ID:
            value: 433
    get:
      summary: Fetch order details
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/Order"
              examples:
                GET_ORDER:
                  value:
                    productid: 10
                    count: 2
                    status: "pending"
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
              examples:
                INVALID_ID:
                  value:
                    timestamp: "2023-03-17T12:06:56.177+00:00"
                    status: 404
                    error: "Not Found"
                    message: "Product with id 344 was not found"
      operationId: get-orders-id
      parameters: []
    post:
      summary: Update order details
      operationId: post-orders-id
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                type: string
              examples:
                UPDATE_ORDER:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/Order"
            examples:
              UPDATE_ORDER:
                value:
                  productid: 10
                  id: 10
                  count: 1
                  status: pending
    delete:
      summary: Cancel an order
      operationId: delete-orders-id
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Cancel successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                DELETE_ORDER:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
  "/inventory/restock":
    post:
      summary: Bulk restock inventory via CSV file
      operationId: bulkRestockInventory
      tags:
        - WIP
      requestBody:
        description: CSV file containing restock transactions
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The CSV file containing the restock details
            examples:
              RESTOCK_CSV:
                value: 
                  file:
                    externalValue: "restock.csv"
      responses:
        "201":
          description: Restock transactions recorded successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    rowNumber:
                      type: integer
                      description: The row number in the CSV file
                    status:
                      type: string
                      description: Status of the restock transaction
                      enum: [success, failure]
                    message:
                      type: string
                      description: Details of the success or failure
                  required:
                    - rowNumber
                    - status
              examples:
                RESTOCK_CSV:
                  value:
                    - rowNumber: 1
                      status: "success"
                      message: "Restock transaction recorded successfully"
                    - rowNumber: 2
                      status: "failure"
                      message: "Invalid product ID"
                    - rowNumber: 3
                      status: "success"
                      message: "Restock transaction recorded successfully"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
components:
  schemas:
    Products_RequestBody:
      required:
        - inventory
        - name
        - type
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - gadget
            - book
            - food
            - other
        inventory:
          type: number
    Orders_RequestBody:
      required:
        - count
        - productid
        - status
      properties:
        productid:
          type: number
        count:
          type: number
        status:
          type: string
          enum:
            - pending
            - fulfilled
            - cancelled
    RestockTransaction:
      type: object
      required:
        - productId
        - quantity
        - date
      properties:
        productId:
          type: integer
          description: ID of the product being restocked
        quantity:
          type: integer
          description: Quantity of the product being added to inventory
        date:
          type: string
          format: date-time
          description: Date and time of the restock transaction
    ErrorResponseBody:
      properties:
        id:
          type: number
        timestamp:
          type: string
        status:
          type: number
        error:
          type: string
        message:
          type: string

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authenticate
